name: Compile and Test

on:
  workflow_dispatch:
    inputs:
      phpversion:
        description: 'PHP Version'
        type: choice
        default: "7.4"
        options:
        - "7.3"
        - "7.4"
        - "8.0"
        - "8.1"  
      runtests:
        description: 'Run Tests'
        type: boolean
        default: true
        required: true
      runvalgrind:
        description: 'Run Tests with Memory Check'
        type: boolean
        default: false
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP and Perl Development
      run: |
        export PHP_VERSION="${{ github.event.inputs.phpversion }}"
        sudo apt-get install "php$PHP_VERSION" "php$PHP_VERSION-dev" libperl-dev
        sudo update-alternatives --set php "/usr/bin/php$PHP_VERSION"
        sudo update-alternatives --set phar "/usr/bin/phar$PHP_VERSION"
        sudo update-alternatives --set phar.phar "/usr/bin/phar.phar$PHP_VERSION"
        sudo update-alternatives --set phpize "/usr/bin/phpize$PHP_VERSION"
        sudo update-alternatives --set php-config "/usr/bin/php-config$PHP_VERSION"
        sudo update-alternatives --set phpdbg "/usr/bin/phpdbg$PHP_VERSION"
    - name: Establish PHP and Perl Versions
      run: |
        php -v
        phpize --version
        perl -v | head -n 2
    - name: Configure PHP Perl Extension
      run: |
        export PHP_PREFIX="/usr"
        export PERL_PREFIX="/usr"
        $PHP_PREFIX/bin/phpize
        ./configure --with-perl=$PERL_PREFIX --with-php-config=$PHP_PREFIX/bin/php-config
        # Non-interactive run-tests
        perl -pi -e 's/(\/run-tests\.php )/$1-q /' Makefile
    - name: Build
      run: make
    - name: Test Extension for Functionality
      if: ${{ github.event.inputs.runtests == 'true' }}
      run: |
        make test
    - name: Install valgrind
      if: ${{ github.event.inputs.runvalgrind == 'true' }}
      run: |
        sudo apt-get install valgrind
        valgrind --version
    - name: Test Extension for Memory Leaks
      if: ${{ github.event.inputs.runvalgrind == 'true' }}
      run: |
        # Suppress this...
        printf "{\n PHP's weird string comparison\n Memcheck:Cond\n fun:zend_string_equal_val\n obj:/usr/bin/php\n}" > php.supp
        echo "--suppressions=$PWD/php.supp" > .valgrindrc
        echo "php.supp" && cat php.supp
        echo ".valgrindrc" && cat .valgrindrc
        # Memory checking run-tests.php
        perl -pi -e 's/(\/run-tests\.php )/$1-m /' Makefile
        make test
