name: Compile and Test

on:
  workflow_dispatch:
    inputs:
      runtests:
        description: 'Run Tests'
        type: boolean
        default: true
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP and Perl Development
      run: |
        sudo apt-get install php7.4-dev libperl-dev
        sudo update-alternatives --set php /usr/bin/php7.4
        sudo update-alternatives --set phar /usr/bin/phar7.4
        sudo update-alternatives --set phar.phar /usr/bin/phar.phar7.4
        sudo update-alternatives --set phpize /usr/bin/phpize7.4
        sudo update-alternatives --set php-config /usr/bin/php-config7.4
    - name: Establish PHP and Perl Versions
      run: |
        php -v
        phpize --version
        perl -v
    - name: Configure PHP Perl Extension
      run: |
        export PHP_PREFIX="/usr"
        export PERL_PREFIX="/usr"
        $PHP_PREFIX/bin/phpize
        ./configure --with-perl=$PERL_PREFIX --with-php-config=$PHP_PREFIX/bin/php-config
    - name: Build
      run: make
    - name: Test Extension
      if: ${{ github.event.inputs.runtests == 'true' }}
      run: make test
