name: Compile and Test

on:
  workflow_dispatch:
    inputs:
      phpversion:
        description: 'PHP Version'
        type: choice
        default: "7.4"
        options:
        - "7.3"
        - "7.4"
        - "8.0"
        - "8.1"  
      runtests:
        description: 'Run Tests'
        type: boolean
        default: true
        required: true
      runvalgrind:
        description: 'Run Tests with Memory Check'
        type: boolean
        default: false
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP and Perl Development
      env:
        PHP_VERSION: "${{ github.event.inputs.phpversion }}"
      run: |
        sudo apt-get install "php$PHP_VERSION" "php$PHP_VERSION-dev" libperl-dev 
        sudo update-alternatives --set php "/usr/bin/php$PHP_VERSION"
        sudo update-alternatives --set phar "/usr/bin/phar$PHP_VERSION"
        sudo update-alternatives --set phar.phar "/usr/bin/phar.phar$PHP_VERSION"
        sudo update-alternatives --set phpize "/usr/bin/phpize$PHP_VERSION"
        sudo update-alternatives --set php-config "/usr/bin/php-config$PHP_VERSION"
        sudo update-alternatives --set phpdbg "/usr/bin/phpdbg$PHP_VERSION"
    - name: Establish PHP and Perl Versions
      run: |
        php -v
        phpize --version
        perl -v | head -n 2
    - name: Configure PHP Perl Extension
      env:
        PHP_PREFIX: "/usr"
        PERL_PREFIX: "/usr"
      run: |
        $PHP_PREFIX/bin/phpize
        ./configure --with-perl=$PERL_PREFIX --with-php-config=$PHP_PREFIX/bin/php-config
        # Non-interactive run-tests
        perl -pi -e 's/(\/run-tests\.php )/$1-q /' Makefile
    - name: Build
      run: make
    - name: Test Extension for Functionality
      if: ${{ github.event.inputs.runtests == 'true' }}
      run: |
        make test
    - name: Install valgrind
      if: ${{ github.event.inputs.runvalgrind == 'true' }}
      run: |
        sudo apt-get install valgrind
        valgrind --version
    - name: Setup Memory Check Suppression File
      env:
        PHP_BIN: "/usr/bin/php${{ github.event.inputs.phpversion }}"
      run: |
        # Suppress these weird PHP things...
        cat << EOF >php_perl.supp 
        {
          PHP's weird string comparison
          Memcheck:Cond
          fun:zend_string_equal_val
          obj:$PHP_BIN
        }
        {
          PHP's print info scandir interaction
          Memcheck:Cond
          obj:$PHP_BIN
          fun:__scandir64_tail
          ...
          fun:php_print_info
        }
        EOF
        echo "Note: Suppressing the following Memory Check Errors" && cat php_perl.supp
    - name: Test Extension for Memory Leaks
      if: ${{ github.event.inputs.runvalgrind == 'true' }}
      env:
        PHP_BIN: "/usr/bin/php${{ github.event.inputs.phpversion }}"
      run: |
        # Suppress these weird PHP things...
        printf "{\n PHP's weird string comparison\n Memcheck:Cond\n fun:zend_string_equal_val\n obj:$PHP_BIN\n}\n" > php_perl.supp
        printf "{\n PHP's print info scandir interaction\n Memcheck:Cond\n obj:$PHP_BIN\n fun:__scandir64_tail\n ...\n fun:php_print_info\n}" >> php_perl.supp
        echo "Note: Suppressing the following Memory Check Errors" && cat php_perl.supp
        echo "--suppressions=$PWD/php_perl.supp" > ~/.valgrindrc
        # Memory checking run-tests.php
        perl -pi -e 's/(\/run-tests\.php )/$1-m /' Makefile
        # Run the tests
        make test
